#!/bin/bash

CHROMIUM_CLI=/usr/bin/chromium
CHROMIUM_MAC=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

if [ -x "$CHROMIUM_CLI" ]; then
  $CHROMIUM_CLI $*
else 
  "$CHROMIUM_MAC" $*
fi